### PR TITLE
Switch to zgenom

### PR DESCRIPTION
**Pull request by unixorn**
# Switch to [zgenom](https://github.com/jandamm/zgenom.git) instead of zgen.

[zgen](https://github.com/tarjoilija/zgen) has been great, but it also hasn't seen any merges to master since 2018.

Fortunately @jandamm has created a new fork of zgen, [zgenom](https://github.com/jandamm/zgenom.git), which they are actively developing. In addition to getting ongoing maintenance, it has new features like lazy loading and `.zshrc` compilation that should help with the speed issues (https://github.com/unixorn/zsh-quickstart-kit/issues/15) some people are seeing. It also supports plugins that do not use a branch named `master` as the default repository branch.

jandamm has been careful to maintain compatibility with zgen in command names and invocations, so it's almost a drop in replacement. I've been running off this branch for weeks without issues, so I'm ready to flip the switch.

### CODE REVIEW

**Comment by jandamm** [comment]
Hi @unixorn,
I'm updating the api of zgenom a little bit.
It'll be possible to use `zgenom` instead of `zgen` and `ohmyzsh` instead of `oh-my-zsh`. The readme is also updated accordingly.
I'm finishing things up and would merge it when you're ready with this PR.

**Comment by unixorn** [comment]
@jandamm If you're updating the api, go ahead merge it into zgenom and tag here when you're done and I'll update this PR accordingly.

I still need to make this PR warn existing users and not just upgrade out from under them. And when they do upgrade, I want them to get the latest greatest zgenom :-)

**Comment by jandamm** [comment]
Done 👍

**Comment by jandamm** [comment]
Hey @unixorn, is there anything I can do to help making progress on this PR?

**Comment by unixorn** [comment]
@jandamm Sorry I let this get dropped - I was busy with other things and lost track of it. Merging.

**Pull request merged**
