### PR TITLE
add ed25519 to list of managed ssh keys

### PR DESCRIPTION
**Pull request by jbreckel**
# License Acceptance

- [x] This repository is Apache version 2.0 licensed (some scripts may have alternate licensing inline in their code) and by making this PR, I am contributing my changes to the repository under the terms of the Apache 2 license.

## Description

Included `ed25519` keys in the `load-our-ssh-keys` function.

## Type of changes

not sure how this would qualify

- [ ] A helper script
- [ ] A link to an external resource like a blog post or video
- [ ] Text cleanups/updates
- [ ] Test updates
- [ ] Bug fix
- [ ] New feature
- [ ] Plugin list change

## Checklist

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have updated the readme if this PR changes/updates quickstart functionality.
- [ ] All new and existing tests pass.
- [ ] Any scripts added use `#!/usr/bin/env interpreter` instead of potentially platform-specific direct paths (`#!/bin/sh` is an allowed exception)
- [ ] Scripts are marked executable
- [ ] Scripts _do not_ have a language file extension unless they are meant to be sourced and not run standalone. No one should have to know if a script was written in bash, python, ruby or whatever. Not including file extensions makes it easier to rewrite the script in another language later without having to change every reference to the previous version.
- [ ] I have added a credit line to README.md for the script
- [ ] If there was no author credit in a script added in this PR, I have added one.
- [ ] I have confirmed that the link(s) in my PR are valid.

### CODE REVIEW

**Review by unixorn — APPROVED** [review]
lgtm

**Comment by unixorn** [comment]
Just waiting on the GH actions to finish and then I'll merge it. Thanks for the contribution!

**Comment by unixorn** [comment]
My bad, I went on vacation and forgot to hit the button - thanks for the contribution.

**Comment by jbreckel** [comment]
hope you had a nice vacation! 
thanks for the merge, love the kit!

**Pull request merged**
